services:
  db:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: blue123
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432" # только для локального доступа (DBeaver и т.д.)
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_user -d task_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend_projects
    container_name: task_manager_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend_projects/.env.docker
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://my_user:blue123@db:5432/task_manager}
      FLASK_ENV: ${FLASK_ENV:-production}
    ports:
      - "5000:5000"
    volumes:
      - ./backend_projects:/app
    command: >
      sh -c "
      flask run --host=0.0.0.0 --port=5000
      "

  frontend:
    build: ./frontend
    container_name: task_manager_frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      sh -c "
      ng serve --host 0.0.0.0 --port 4200 --poll=2000
      "

volumes:
  pgdata:
