services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: blue123
      POSTGRES_DB: task_manager
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend_projects
    depends_on:
      - db
    env_file:
      - ./backend_projects/.env.docker
    ports:
      - "5000:5000"
    volumes:
      - ./backend_projects:/app
    command: >
      sh -c "while ! nc -z db 5432; do echo 'Waiting for DB...'; sleep 1; done;
             flask run --host=0.0.0.0 --reload"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: >
      ng serve --host 0.0.0.0 --port 4200 --poll=2000

volumes:
  pgdata:
